
 #Port
server:
  port: 9091
#Database connection
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: ies
    password: ies
    driver-class-name: oracle.jdbc.driver.OracleDriver
#Loggin
#logging:
 # file: SSAWeb-App.log
  #level:
   # root: INFO
    #com.usa.ri.gov.ies: DEBUG